export const usernames = [
  "john.doe",
  "jane.doe",
  "peter.pan",
  "wendy.darling",
  "captain.hook",
  "alice.wonderland",
  "mad.hatter",
  "cheshire.cat",
  "dormouse",
  "white.rabbit",
  "harry.potter",
  "hermione.granger",
  "ron.weasley",
  "voldemort",
  "hagrid",
  "luke.skywalker",
  "leia.organa",
  "han.solo",
  "darth.vader",
  "yoda",
  "neo",
  "trinity",
  "morpheus",
  "agent.smith",
  "oracle",
  "gandalf",
  "aragorn",
  "legolas",
  "gimli",
  "frodo.baggins",
  "bilbo.baggins",
  "samwise.gamgee",
  "gollum",
  "sauron",
  "saruman",
  "batman",
  "superman",
  "wonder.woman",
  "flash",
  "aquaman",
  "green.lantern",
  "cyborg",
  "shazam",
  "joker",
  "harley.quinn",
];
export const generateRandomTurnover = () => {
  const min = 1000;
  const max = 1000000;
  const randomNum = Math.floor(Math.random() * (max - min + 1)) + min;
  return randomNum.toString();
};
